name: Build and Release luci-app-webpanel (SDK)

on: 
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up OpenWrt SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev zlib1g-dev wget
        # 下载 Mediatek Filogic 架构的 SDK (23.05 版本)
        SDK_URL="https://downloads.openwrt.org/releases/23.05.0/targets/mediatek/filogic/openwrt-sdk-23.05.0-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64.tar.xz"
        wget $SDK_URL
        tar xf openwrt-sdk-*.tar.xz
        rm openwrt-sdk-23.05.0-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64.tar.xz
        cd openwrt-sdk-*
        echo "SDK_PATH=$PWD" >> $GITHUB_ENV
        
    - name: Prepare plugin
      run: |
        mkdir -p $SDK_PATH/package/luci-app-webpanel
        cp -r luasrc $SDK_PATH/package/luci-app-webpanel/
        cp -r root $SDK_PATH/package/luci-app-webpanel/
        cp Makefile $SDK_PATH/package/luci-app-webpanel/
        # 确保 feeds 已更新
        $SDK_PATH/scripts/feeds update -a
        $SDK_PATH/scripts/feeds install -a
        
    - name: Build package
      run: |
        cd $SDK_PATH
        # 生成默认配置
        cat > .config <<EOF
        CONFIG_TARGET_mediatek=y
        CONFIG_TARGET_mediatek_filogic=y
        CONFIG_PACKAGE_luci-app-webpanel=y
        CONFIG_PACKAGE_luci-i18n-webpanel-zh-cn=y
        EOF
        make defconfig
        # 编译插件 (失败时显示详细日志)
        make package/luci-app-webpanel/compile -j$(nproc) || make package/luci-app-webpanel/compile V=s
        
    - name: Collect artifacts
      run: |
        mkdir -p artifacts
        find $SDK_PATH/bin -name "luci-app-webpanel*.ipk" -exec cp {} artifacts/ \;
        find $SDK_PATH/bin -name "luci-i18n-webpanel-zh-cn*.ipk" -exec cp {} artifacts/ \;
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ipk-packages
        path: artifacts/
        
  release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: ipk-packages
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        body: |
          OpenWrt 23.05 Web Panel 插件包 (Mediatek Filogic 架构)
          功能特性:
          - 可配置多个内嵌网页
          - 支持自定义URL和端口
          - 标签页切换管理
          包含文件:
          - luci-app-webpanel_*.ipk
          - luci-i18n-webpanel-zh-cn_*.ipk
        files: |
          *.ipk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
