name: Build LuCI Web Panel Plugin

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk: 
          - 'openwrt-sdk-23.05.0-x86-64_gcc-12.3.0_musl.Linux-x86_64'
          - 'openwrt-sdk-22.03.5-x86-64_gcc-11.2.0_musl.Linux-x86_64'
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up SDK
      run: |
        SDK_URL="https://downloads.openwrt.org/releases/$(echo ${{ matrix.sdk }} | cut -d'-' -f3)/targets/$(echo ${{ matrix.sdk }} | cut -d'-' -f4)/$(echo ${{ matrix.sdk }} | cut -d'-' -f5)/${{ matrix.sdk }}.tar.xz"
        echo "Downloading SDK from: $SDK_URL"
        wget $SDK_URL -O sdk.tar.xz
        tar -xf sdk.tar.xz
        mv ${{ matrix.sdk }} openwrt-sdk
        echo "SDK_PATH=$(pwd)/openwrt-sdk" >> $GITHUB_ENV
    
    - name: Build package
      run: |
        # 复制文件到正确位置
        mkdir -p $SDK_PATH/package/luci-app-webpanel
        cp -r ./files $SDK_PATH/package/luci-app-webpanel/
        cp ./Makefile $SDK_PATH/package/luci-app-webpanel/
        
        # 进入SDK目录
        cd $SDK_PATH
        
        # 更新feeds
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        
        # 构建包
        make package/luci-app-webpanel/compile V=s
        
        # 复制生成的IPK文件
        mkdir -p ../artifacts/${{ matrix.sdk }}
        find bin/ -name "luci-app-webpanel*.ipk" -exec cp {} ../artifacts/${{ matrix.sdk }} \;
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ipk-packages
        path: artifacts/
        if-no-files-found: error
